# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json
# Configuraci贸n de CodeRabbit para firmware ESP32-S3

language: "es"

reviews:
  auto_review:
    enabled: true
    drafts: false

  review_status: true
  profile: "assertive"

  request_changes_workflow: false
  high_level_summary: true
  high_level_summary_placeholder: "**Resumen de cambios**"
  poem: false
  review_status_comment: true
  collapse_walkthrough: false
  auto_incremental_review: true

  tools:
    ruff:
      enabled: false
    shellcheck:
      enabled: true

#  Nueva forma correcta de dar instrucciones
guidelines:
  - "Firmware embebido ESP32-S3 con PlatformIO"
  - "Priorizar seguridad, manejo de errores y uso eficiente de memoria"
  - "Revisar inicializaci贸n correcta de perif茅ricos (I2C, SPI, PWM)"
  - "Validar watchdog y recuperaci贸n ante bloqueos"
  - "Detectar posibles memory leaks y buffer overflows"
  - "Comprobar manejo robusto de sensores y fallos"
  - "Detectar condiciones de carrera o bloqueos entre tasks"
  - "Comprobar rangos de arrays y l铆mites de buffers"

chat:
  auto_reply: false

knowledge_base:
  learnings:
    core_architecture:
      path: "src/core"
      content: |
        Arquitectura basada en managers:

        - PowerManager
        - SafetyManager
        - SensorManager
        - ControlManager
        - HUDManager

        Sistemas clave:
        - watchdog
        - logging
        - tolerancia a fallos
        - recuperaci贸n segura

    components_technology:
      path: "**/*.cpp"
      content: |
        Componentes principales:
        - ABS / TCS
        - HUD TFT 480x320
        - INA226, DS18B20
        - WS2812B
        - MCP23017
        - DFPlayer