# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json

language: "es"

reviews:
  auto_review:
    enabled: true
    drafts: false

  review_status: true
  profile: "assertive"
  high_level_summary: true
  high_level_summary_placeholder: "**Resumen de cambios**"
  request_changes_workflow: false
  poem: false
  collapse_walkthrough: false
  auto_incremental_review: true

chat:
  auto_reply: false

knowledge_base:
  learnings:
    core_architecture:
      path: "src/core"
      content: |
        Firmware ESP32-S3 basado en managers:
        PowerManager, SafetyManager, SensorManager, ControlManager, HUDManager.

        Prioridad:
        - seguridad
        - tolerancia a fallos
        - watchdog
        - logging
        - recuperación segura

    components_technology:
      path: "**/*.cpp"
      content: |
        Tecnologías:
        - ABS / TCS
        - HUD TFT
        - INA226, DS18B20
        - LEDs WS2812B
        - DFPlayer
        - MCP23017